baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'matt clawson'
theme = 'hugo-coder'
defaultcontentlanguage = "en"

[params]
  author = "Matt Clawson"
  info = "Data Engineer"
  description = "Matt Clawson's personal site"
  keywords = "blog,developer,personal"
  avatarurl = "images/headshot.jpg"

  faviconSVG = "/images/ij-circle-white.svg"
  favicon_32 = "/images/ij-circle-white.png"
  favicon_16 = "/images/ij-circle-white.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

# menu links
[[menu.main]]
  name = "now"
  weight = 1
  url  = "now/"

[[menu.main]]
  name = "about"
  weight = 2
  url  = "about/"

[[menu.main]]
  name = "blog"
  weight = 3
  url  = "posts/"

# socials
[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/mbclawson"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/matthew-clawson-1b8b6b30/"

